# Import libraries

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import sklearn

# Understanding Data

In [2]:
Weather_data=pd.read_csv("environmental_data.csv")
Weather_data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

In [3]:
Weather_data.shape

(158, 10)

In [4]:
print(Weather_data.columns.tolist())

['Unnamed: 0', 'Ozone', 'Solar.R', 'Wind', 'Temp C', 'Month', 'Day', 'Year', 'Temp', 'Weather']

In [5]:
Weather_data.drop(labels=["Temp C","Unnamed: 0"],axis=1,inplace=True)
Weather_data

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0     41.0    190.0   7.4     5    1  2010    67       S
1     36.0    118.0   8.0     5    2  2010    72       C
2     12.0    149.0  12.6     5    3  2010    74      PS
3     18.0    313.0  11.5     5    4  2010    62       S
4      NaN      NaN  14.3     5    5  2010    56       S
..     ...      ...   ...   ...  ...   ...   ...     ...
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

[158 rows x 8 columns]

In [6]:
Weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [7]:
Weather_data.describe()

            Ozone     Solar.R        Wind         Day    Year        Temp
count  120.000000  151.000000  158.000000  158.000000   158.0  158.000000
mean    41.583333  185.403974    9.957595   16.006329  2010.0   77.727848
std     32.620709   88.723103    3.511261    8.997166     0.0    9.377877
min      1.000000    7.000000    1.700000    1.000000  2010.0   56.000000
25%     18.000000  119.000000    7.400000    8.000000  2010.0   72.000000
50%     30.500000  197.000000    9.700000   16.000000  2010.0   78.500000
75%     61.500000  257.000000   11.875000   24.000000  2010.0   84.000000
max    168.000000  334.000000   20.700000   31.000000  2010.0   97.000000

# Data preprocessing

In [8]:
Weather_data.head(10)

   Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     5    1  2010    67       S
1   36.0    118.0   8.0     5    2  2010    72       C
2   12.0    149.0  12.6     5    3  2010    74      PS
3   18.0    313.0  11.5     5    4  2010    62       S
4    NaN      NaN  14.3     5    5  2010    56       S
5   28.0      NaN  14.9     5    6  2010    66       C
6   23.0    299.0   8.6     5    7  2010    65      PS
7   19.0     99.0  13.8     5    8  2010    59       C
8    8.0     19.0  20.1     5    9  2010    61      PS
9    NaN    194.0   8.6     5   10  2010    69       S

In [9]:
Weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [10]:
Weather_data.shape

(158, 8)

In [11]:
print(Weather_data["Ozone"].isnull().sum())

38

In [12]:
38/158

0.24050632911392406

In [13]:
Weather_data.drop(labels=["Ozone"],axis=1,inplace=True,errors="ignore")
Weather_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4        NaN  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

* Your notebook removes Ozone because 38 out of 158 values are missing (approximately 24.1%).
* This is a reasonable preprocessing decision for your exercise, but in a professional project, mention that you evaluated the missingness and chose     column removal rather than testing imputation alternatives.

In [14]:
7/158

0.04430379746835443

* Here, there is only 4 percentage of null values are present in the Solar.R feature. So it can be replace by find the mean of feature

In [23]:
Weather_data.groupby("Weather")["Solar.R"].mean().round()

Weather
C     192.0
PS    174.0
S     193.0
Name: Solar.R, dtype: float64

In [24]:
Weather_data["Solar.R"] = Weather_data["Solar.R"].fillna(
    Weather_data.groupby("Weather")["Solar.R"].transform("mean").round(0)
).round(0)

In [25]:
Weather_data["Solar.R"]

0      190.0
1      118.0
2      149.0
3      313.0
4      193.0
       ...
153    190.0
154    193.0
155    145.0
156    191.0
157    131.0
Name: Solar.R, Length: 158, dtype: float64

In [26]:
Weather_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4      193.0  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

In [27]:
Weather_data.isna().sum()

Solar.R    1
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [28]:
Weather_data[Weather_data["Weather"].isnull()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87     82.0  12.0     7   27  2010    86     NaN
93     24.0  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [29]:
Weather_data.dropna(subset=["Weather"], inplace=True)

In [30]:
Weather_data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [31]:
Weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [32]:
print(Weather_data["Month"].unique())

['5' 'May' '6' '7' '8' '9']

In [33]:
Weather_data["Month"].replace("May", "5", inplace=True)
Weather_data["Month"]

0      5
1      5
2      5
3      5
4      5
      ..
153    5
154    9
155    9
156    9
157    9
Name: Month, Length: 155, dtype: object

In [34]:
print(Weather_data["Month"].unique())

['5' '6' '7' '8' '9']

In [35]:
Weather_data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [36]:
Weather_data["Month"]=Weather_data["Month"].astype("int")

In [37]:
Weather_data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

# Data Transformation

In [38]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

### Lable Encoder

In [41]:
Le_encoder=LabelEncoder()

In [42]:
Weather_data_copy_1=Weather_data.copy()

In [43]:
Le_encoder.fit_transform(Weather_data_copy_1["Weather"])

array([2, 0, 1, 2, 2, 0, 1, 0, 1, 2, 0, 1, 2, 2, 0, 2, 2, 0, 1, 2, 2, 0,
       1, 0, 1, 0, 1, 2, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2,
       2, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 2,
       0, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 2, 0, 1, 0, 2, 2, 0, 1, 1, 0, 2,
       0, 1, 0, 1, 1, 2, 0, 0, 1, 0, 1, 2, 2, 2, 0, 0, 0, 1, 0, 1, 2, 2,
       0, 1, 0, 1, 2, 2, 2, 2, 2, 0, 0, 1, 0, 1, 2, 2, 2, 0, 1, 0, 1, 2,
       2, 1, 1, 2, 1, 2, 0, 1, 1, 2, 2, 0, 1, 0, 1, 2, 1, 2, 0, 1, 2, 2,
       0])

In [44]:
Weather_data_copy_1["Weather"]=Le_encoder.fit_transform(Weather_data_copy_1["Weather"])
Weather_data_copy_1

     Solar.R  Wind  Month  Day  Year  Temp  Weather
0      190.0   7.4      5    1  2010    67        2
1      118.0   8.0      5    2  2010    72        0
2      149.0  12.6      5    3  2010    74        1
3      313.0  11.5      5    4  2010    62        2
4      193.0  14.3      5    5  2010    56        2
..       ...   ...    ...  ...   ...   ...      ...
153    190.0   7.4      5    1  2010    67        0
154    193.0   6.9      9   26  2010    70        1
155    145.0  13.2      9   27  2010    77        2
156    191.0  14.3      9   28  2010    75        2
157    131.0   8.0      9   29  2010    76        0

[155 rows x 7 columns]

In [45]:
Weather_data_copy_1["Weather"]=Weather_data_copy_1["Weather"].astype("int")
Weather_data_copy_1

     Solar.R  Wind  Month  Day  Year  Temp  Weather
0      190.0   7.4      5    1  2010    67        2
1      118.0   8.0      5    2  2010    72        0
2      149.0  12.6      5    3  2010    74        1
3      313.0  11.5      5    4  2010    62        2
4      193.0  14.3      5    5  2010    56        2
..       ...   ...    ...  ...   ...   ...      ...
153    190.0   7.4      5    1  2010    67        0
154    193.0   6.9      9   26  2010    70        1
155    145.0  13.2      9   27  2010    77        2
156    191.0  14.3      9   28  2010    75        2
157    131.0   8.0      9   29  2010    76        0

[155 rows x 7 columns]

In [46]:
Weather_data_copy_1.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather      int64
dtype: object

In [ ]:
print("Final Dataset Shape:", Weather_data_copy_1.shape)

print("\nMissing Values:")
print(Weather_data_copy_1.isnull().sum())

print("\nData Types:")
print(Weather_data_copy_1.dtypes)

print("\nFinal Dataset:")
display(Weather_data_copy_2.head())

### OneHotEncoder

In [47]:
OHE=OneHotEncoder()

In [48]:
Weather_data_copy_2=Weather_data.copy()

In [49]:
Weather_data_copy_2 = Weather_data.copy()

Weather_data_copy_2 = pd.get_dummies(
    Weather_data_copy_2,
    columns=["Weather"],
    dtype=int
)

In [50]:
Weather_data_copy_2

     Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4      5    1  2010    67          0           0          1
1      118.0   8.0      5    2  2010    72          1           0          0
2      149.0  12.6      5    3  2010    74          0           1          0
3      313.0  11.5      5    4  2010    62          0           0          1
4      193.0  14.3      5    5  2010    56          0           0          1
..       ...   ...    ...  ...   ...   ...        ...         ...        ...
153    190.0   7.4      5    1  2010    67          1           0          0
154    193.0   6.9      9   26  2010    70          0           1          0
155    145.0  13.2      9   27  2010    77          0           0          1
156    191.0  14.3      9   28  2010    75          0           0          1
157    131.0   8.0      9   29  2010    76          1           0          0

[155 rows x 9 columns]

In [51]:
Weather_data_copy_2.dtypes

Solar.R       float64
Wind          float64
Month           int64
Day             int64
Year            int64
Temp            int64
Weather_C       int64
Weather_PS      int64
Weather_S       int64
dtype: object

In [52]:
print("Final Dataset Shape:", Weather_data_copy_2.shape)

print("\nMissing Values:")
print(Weather_data_copy_2.isnull().sum())

print("\nData Types:")
print(Weather_data_copy_2.dtypes)

print("\nFinal Dataset:")
display(Weather_data_copy_2.head())

Final Dataset Shape: (155, 9)

Missing Values:
Solar.R       0
Wind          0
Month         0
Day           0
Year          0
Temp          0
Weather_C     0
Weather_PS    0
Weather_S     0
dtype: int64

Data Types:
Solar.R       float64
Wind          float64
Month           int64
Day             int64
Year            int64
Temp            int64
Weather_C       int64
Weather_PS      int64
Weather_S       int64
dtype: object

Final Dataset:

   Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0    190.0   7.4      5    1  2010    67          0           0          1
1    118.0   8.0      5    2  2010    72          1           0          0
2    149.0  12.6      5    3  2010    74          0           1          0
3    313.0  11.5      5    4  2010    62          0           0          1
4    193.0  14.3      5    5  2010    56          0           0          1